'use client';
import { useCallback, useEffect, useState } from 'react';
import { Plus, RefreshCw } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import styles from './admin-dashboard.module.css';
type Voice = { id: string; name: string; voice_description: string; sample_text: string; language: string; seed: number; status: string; error_message?: string | null; created_at: string };
async function token() { const session = await supabase?.auth.getSession(); const value = session?.data.session?.access_token; if (!value) throw new Error('Sign in with the owner account.'); return value; }
export function AdminVoices() {
  const [voices, setVoices] = useState<Voice[]>([]), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const [name, setName] = useState(''), [description, setDescription] = useState(''), [sample, setSample] = useState('Every story begins with a choice. Take a breath, trust your instincts, and let the next moment reveal itself.'), [seed, setSeed] = useState('729754692978412');
  const load = useCallback(async () => { try { const access = await token(); const response = await fetch('/api/admin/voices', { headers: { Authorization: `Bearer ${access}` }, cache: 'no-store' }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setVoices(body.voices); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Voice library is unavailable.'); } }, []);
  useEffect(() => { queueMicrotask(() => { void load(); }); }, [load]);
  useEffect(() => { const timer = setInterval(() => { if (voices.some(v => v.status === 'queued' || v.status === 'running')) void Promise.all(voices.filter(v => v.status === 'queued' || v.status === 'running').map(async voice => { const access = await token(); await fetch(`/api/admin/voices/${voice.id}`, { headers: { Authorization: `Bearer ${access}` } }); })).then(load); }, 5000); return () => clearInterval(timer); }, [voices, load]);
  async function create(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { const access = await token(); const response = await fetch('/api/admin/voices', { method: 'POST', headers: { Authorization: `Bearer ${access}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ name, voiceDescription: description, sampleText: sample, language: 'English', seed: Number(seed) }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setName(''); setDescription(''); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Voice creation failed.'); } finally { setBusy(false); } }
  return <main className={styles.admin}><header className={styles.header}><span>Platform voices</span><button onClick={() => void load()}><RefreshCw size={16} /> Refresh</button></header><div className={styles.heading}><div><h1>Voice library</h1><p>Create approved character voices with Qwen VoiceDesign, then make them available in ClipWeave.</p></div></div>
    <section><h2>Create a voice</h2><form className={styles.controls} onSubmit={create}><label>Name<input required value={name} onChange={e => setName(e.target.value)} placeholder="Nia — warm Nigerian alto" /></label><label>Voice description<textarea required value={description} onChange={e => setDescription(e.target.value)} placeholder="Describe accent, age, pitch, pace, texture, and emotional quality." /></label><label>Preview script<textarea required value={sample} onChange={e => setSample(e.target.value)} /></label><label>Seed<input required type="number" value={seed} onChange={e => setSeed(e.target.value)} /></label><button disabled={busy}><Plus size={16} /> {busy ? 'Queuing…' : 'Create voice'}</button></form>{error && <p className={styles.warning} role="alert">{error}</p>}</section>
    <section><h2>Generated voices</h2>{voices.length ? <div className={styles.tableWrap}><table><thead><tr><th>Name</th><th>Description</th><th>Status</th><th>Created</th></tr></thead><tbody>{voices.map(voice => <tr key={voice.id}><td>{voice.name}</td><td>{voice.voice_description}<small>Seed {voice.seed}</small></td><td><span className={styles.status} data-status={voice.status === 'ready' ? 'completed' : voice.status === 'failed' ? 'failed' : undefined}>{voice.status}</span>{voice.error_message && <small>{voice.error_message}</small>}</td><td>{new Date(voice.created_at).toLocaleString()}</td></tr>)}</tbody></table></div> : <p>No platform voices yet.</p>}</section></main>;
}
